"use client";

import { motion } from "framer-motion";
import { Activity, BrainCircuit, Clock3, Code2, Flame, Sparkles } from "lucide-react";
import { GlassCard, PageTransition, PanelHeader } from "@/components/ui/primitives";
import { AreaChart, BarChart, Donut, Heatmap } from "@/components/ui/charts";
import { analytics } from "@/lib/data/seed";

const focus = analytics.focusHours14d;
const avgFocus = (focus.reduce((a, b) => a + b, 0) / focus.length).toFixed(1);
const codingWeek = analytics.codingByWeekday.reduce((a, d) => a + d.value, 0).toFixed(0);
const prodNow = analytics.productivity30d[analytics.productivity30d.length - 1];

const STATS = [
  { label: "Avg focus / day", value: `${avgFocus}h`, icon: Clock3, color: "#00e5ff" },
  { label: "Coding this week", value: `${codingWeek}h`, icon: Code2, color: "#a78bfa" },
  { label: "Productivity", value: `${prodNow}/100`, icon: Activity, color: "#34d399" },
  { label: "Best streak", value: "11 days", icon: Flame, color: "#f59e0b" },
];

export default function AnalyticsScreen() {
  return (
    <PageTransition className="mx-auto flex max-w-6xl flex-col gap-4">
      <header>
        <h1 className="font-display text-[18px] tracking-[0.22em] text-cyan-50 uppercase" style={{ textShadow: "0 0 18px rgba(0,229,255,0.35)" }}>
          Analytics Core
        </h1>
        <p className="mt-1 text-[13px] text-dim">Telemetry over the last 30 days · insights generated by the research agent</p>
      </header>

      {/* Stat strip */}
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        {STATS.map((s, i) => (
          <motion.div key={s.label} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.06 }}>
            <GlassCard className="flex items-center gap-3 px-4 py-3.5">
              <span className="grid h-10 w-10 place-items-center rounded-xl border" style={{ borderColor: `${s.color}45`, background: `${s.color}0d`, color: s.color }}>
                <s.icon size={17} />
              </span>
              <div>
                <div className="font-display text-[19px] leading-none text-cyan-50" style={{ textShadow: `0 0 14px ${s.color}55` }}>{s.value}</div>
                <div className="hud-label mt-1 !text-[9px]">{s.label}</div>
              </div>
            </GlassCard>
          </motion.div>
        ))}
      </div>

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">
        <GlassCard corners className="p-5">
          <PanelHeader icon={<Clock3 size={14} />} title="Focus Hours — 14 days" />
          <AreaChart data={focus} yLabel="HOURS" />
        </GlassCard>

        <GlassCard corners className="p-5">
          <PanelHeader icon={<Code2 size={14} />} title="Coding Time by Weekday" />
          <BarChart data={analytics.codingByWeekday} color="#a78bfa" unit="h" />
        </GlassCard>

        <GlassCard corners className="p-5">
          <PanelHeader icon={<Activity size={14} />} title="Productivity Score — 30 days" />
          <AreaChart data={analytics.productivity30d} color="#34d399" yLabel="SCORE" />
        </GlassCard>

        <GlassCard corners className="p-5">
          <PanelHeader icon={<Flame size={14} />} title="Task Completion + Consistency" />
          <div className="flex flex-wrap items-center gap-6">
            <div className="flex items-center gap-4">
              <Donut segments={analytics.completionByCategory} />
              <div className="flex flex-col gap-1.5">
                {analytics.completionByCategory.map((s) => (
                  <div key={s.label} className="flex items-center gap-2 text-[12.5px]">
                    <span className="h-2 w-2 rounded-full" style={{ background: s.color, boxShadow: `0 0 6px ${s.color}` }} />
                    <span className="w-20 text-dim">{s.label}</span>
                    <span className="font-display text-[11px] text-icy">{s.value}%</span>
                  </div>
                ))}
              </div>
            </div>
            <div>
              <div className="hud-label mb-2 !text-[9px]">12-week consistency</div>
              <Heatmap grid={analytics.consistency} />
            </div>
          </div>
        </GlassCard>
      </div>

      {/* AI insights */}
      <GlassCard corners className="p-5">
        <PanelHeader icon={<BrainCircuit size={14} />} title="AI-Generated Insights" right={<Sparkles size={13} className="text-cyan-400/60" />} />
        <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
          {analytics.insights.map((ins, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.2 + i * 0.1 }}
              className={`rounded-xl border p-3.5 text-[13.5px] leading-relaxed ${
                ins.kind === "warning"
                  ? "border-amber-400/30 bg-amber-400/[0.05] text-amber-100/90"
                  : "border-emerald-400/30 bg-emerald-400/[0.05] text-emerald-100/90"
              }`}
            >
              {ins.text}
            </motion.div>
          ))}
        </div>
      </GlassCard>
    </PageTransition>
  );
}
